### ISSUE TITLE
Gestion des utilisateurs avec UsersHub

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoPaysages#1]
L'application UsersHub (https://github.com/PnEcrins/UsersHub) permet d'administrer une schéma PG ``utilisateurs`` regroupant les utilisateurs, les groupes d'utilisateur, leurs droits, les listes d'utilisateurs, les différentes applications...

Ce schéma peut être répliqué ou accédé par des BDD tiers pour ne pas avoir à gérer des comptes utilisateurs dans chacunes de nos applications mais les gérer de manière centralisées. 

Pour utiliser facilement l'authentification dans une application Flask, un sous-module a été créé : https://github.com/PnX-SI/UsersHub-authentification-module.

Il peut-être installé automatiquement lors de l'installation de l'application et on bénéficie directement dans l'application de toutes ses routes. Exemple : https://github.com/PnX-SI/GeoNature/blob/master/backend/requirements.txt#L13

Dans le CCTP (http://geonature.fr/documents/autres/geopaysages/2017-11-13-CDC-OPPV-PNV.pdf), il est indiqué une table des utilisateurs de cette manière : 

> t_utilisateur = table de gestion des profils et des utilisateur du back-office et des auteurs de photo
>  id_role = identifiant unique de l'utilisateur
>  id_right = niveau de droits de l'utilisateur (1 à 6, 6 étant super-administrateur. Le libellé des valeurs
> sera fourni) => Les valeurs de ce champ seront utilisées pour définir les droits des utilisateurs sur les
> fonctionnalités du back-office.
>  author_photo = auteur de photo (oui/non)
>  id_application = identifiant de l'application OPP défini dans UsersHub
>  name = nom de l'utilisateur
>  first_name = prénom de l'utilisateur
>  organization = structure de rattachement de l'utilisateur
>  mail = e-mail de l'utilisateur
>  path_author_photo = chemin de la photo de l'auteur de photo des paysages

Cela comprend quelques incohérences avec le schéma ``utilisateurs`` de UsersHub qui se base sur une table ``t_roles`` regroupant utilisateurs et groupes. Il y a aussi des vues (et leurs routes) qui permettent de récupérer les droits d'un utilisateur en fonction de ses éventuelles groupes et par application.

En effet dans le CCTP, si on utilise UsersHub, alors il est plutôt prévu que l'application n'utilise pas directement le schéma ``utilisateur`` mais plutôt l'utilise pour remplir la table ``t_utilisateur``.

A voir ce qui est le plus pertinent. 

Dans tous les cas, il est indiqué dans le CCTP des valeurs en dur de ``utilisateurs.cor_role_menu.id_menu = 100``. Il est important que celles-ci soient configurables pour permettre de s'adapter à différents cas.

**Comment by cdcvidal** [comment]
Nous allons utiliser le sous-module https://github.com/PnX-SI/UsersHub-authentification-module.

Parcontre, nous ne comprenons pas l'interêt de la table oppv.t_utilisateur. 
Pourquoi ne pas mettre directement l'id_role de la table utilisateurs.t_roles en référence de la table oppv.t_photo ?

**Comment by camillemonchicourt** [comment]
Oui comme je disais c'est un choix à faire.

Je laisse le PNV voir ce qu'ils en pensent.

**Comment by Chrispnv** [comment]
Bonjour,

La table utilisateur est là pour les structures qui n'ont pas usershub. 
Dans le cas contraire, c'est le schéma utilisateurs qui est utilisé. Les 
auteurs des photos seront créés dans usershub et mis dans une liste 
d'auteurs avec un rôle observateur et sans login/mot de passe ne donnant 
pas d'accès au back-office de l'application.

Bonne journée.

Untitled Document
------------------------------------------------------------------------
		Christophe CHILLET
Responsable de l'unité Système d'information

Parc national de la Vanoise
Tél : +33(0)4 79 62 90 16 - Fax : +33 (0)4 79 96 37 18
www.vanoise-parcnational.fr <http://www.vanoise-parcnational.fr/>
rando.vanoise.com <http://rando.vanoise.com/fr/>

<https://www.facebook.com/parcnationaldelavanoise> 
<https://twitter.com/pnvanoise> 
<https://www.youtube.com/user/ParcNationalVanoise>
		Faites un geste pour l'environnement : n'imprimez ce message qu'en cas 
de nécessité

Le 11/10/2018 à 11:46, Camille Monchicourt a écrit :

**Comment by Chrispnv** [comment]
On a réfléchi à nouveau à la la liaison appli observatoire paysage usershub avec Camille et ma collègue Claire Lagaye.
Le mieux sera de supprimer cette table t_utilisateur dans le schema public de la bdd oppv. Pour les structures n'utilisant pas usershub, ils peupleront par leurs moyens propres les tables du schéma utilisateur de la bdd oppv. Comme cela pas de double développement.

Donc le schema utilisateur de la bdd oppv sera peuplé depuis usershub avec des auteurs et des contributeurs dans la table t_role.
Les auteurs n'ont pas de login/mdp et ils viennent alimenter une liste (on pourrait l'appeler auteurs_geopaysage). La liste des auteurs dans le BO sur l'ajout d'une photo vient de la table cor_role_menu en prenant les auteurs liés à la liste auteurs_geopaysage.
Les contributeurs seront dans la table cor_role_droit_application qui sera utilisé pour les utilisateurs pouvant se connecter au BO.

Concernant le lien entre l'auteur (role) et les photos, pour une question de meilleure compréhension, le champ id_author de la table t_photo deviendra id_role. Donc l'id_role de l'auteur choisi dans la liste des auteurs sur l'ajout ou la modif d'une photo dans le BO viendra alimenter le champ id_role de la table t_photo.

**Comment by cdcvidal** [comment]
Merci pour ces informations
Pouvez-vous nous fournir un nouveau MCD et un script d'insert d'utilisateur et oppv afin de clarifier les changements au niveau de la base de données ?

**Comment by camillemonchicourt** [comment]
Ne pas dupliquer le SQL de création du schéma ``utilisateurs``dans le dépôt mais se baser sur celui du dépôt de UsersHub. 

Voir le fonctionnement de TaxHub par exemple : https://github.com/PnX-SI/TaxHub/blob/master/install_db.sh#L119-L128

**Comment by camillemonchicourt** [comment]
En effet on ne devrait pas dupliquer le script SQL de UsersHub mais se baser sur celui de UsersHub directement, en faisant appel à une version fixée dans les paramètres d'installation de GeoPaysages.

**Comment by camillemonchicourt** [comment]
Fait par @xavyeah39 dans https://github.com/PnX-SI/GeoPaysages/pull/99
