### ISSUE TITLE
Comparateur photos v2 - CSS et internationalisation 

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoPaysages#100]
En testant la v2 du comparateur photos je constate que : 

- le CSS sur les textes n'est pas harmonisé (idem sur le texte des filtres actifs dans la sidebar de la page carte),
- l'internationalisation des textes dans le le template HTML ``comparator-v2.html`` n'est pas implémentée,
- Certains libellés de textes sont inscrit "en dur" dans le JS ``comparator-v2.js``

**Comment by xavyeah39** [comment]
Propositions pour régler les 2 premiers points dans la PR #101 et les commits 31f8280  et 49353a0.
Pour les textes en FR inscrits en dur dans le JS, je n'ai pas trouvé de solution.

**Comment by camillemonchicourt** [comment]
Merci, @20cents je te laisse relire et valider/compléter la PR pour corriger ces soucis du comparateur V2 ?
Merci d'avance.
