### ISSUE TITLE
Comparateur photos v2 - Conf et personnalisation ??

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoPaysages#102]
Après avoir testé cette V2 du comparateur dans notre contexte OPP (PNR), je trouve que celui-ci ne correspond pas tout à fait au contexte "habituels" des OPP avec, le plus souvent, des reconductions de photos sur des pas de temps plutôt espacés (annuelles voire pluriannuelles par exemple).

Voici mon analyse + des propositions de légères évolutions :

- L'outil de filtres par date de début et fin me semble complexifier un peu la navigation lorsque que l'on a pas de grosses séries de photos sur les sites. Chez nous l'OPP est un des plus anciens (depuis 1994) mais avec des reconductions annuelles, cela ne nous fait pas plus de 30 photos par sites (donc maximum 3 pages dans lesquels naviguer). De plus le filtre fonctionne avec des plages de dates précises `jj/mm/yyyy` qui n'ont guère de sens dans le cas de photos renseignées avec des dates imprécises (cf. dernier point)

    **Solution proposée :** pouvoir masquer le filtre par dates via un paramètre `comparator_date_filter` dans la table `conf` de la BDD. Celui-ci prend comme valeur `True` ou `False`. Si le paramètre n'est pas défini, le filtre s'affiche par défaut. 
Voir commit bf584edd8fdb3ed0a66e2794994f992328953dcd

- Dans les cas où l'on a un seul pas de temps de reconduction des photos (annuelle par exemple), le bouton sélecteur de pas de temps n'est pas très utile et seuls les boutons précédent/suivant ont vraiment du sens. 

    **Solution proposée :** pouvoir masquer le bouton sélecteur de pas de temps via un paramètre `comparator_date_step_button` (`True` ou `False`) dans la table `conf` de la BDD. 
Voir commit bbc50b7216a1560d04231c8e29ad73a0caae1f21

- l'affichage de la date complète dans les sélecteurs et les filtres n'est pas des plus adaptée. Sur les photos anciennes, nous n'avons pas les dates précises des clichés. Dans ce cas, nous avons tout même renseigné le champ `filter_date` (format date) avec 1994-01-01 par exemple afin qu'un filtrage par date (même imprécise) soit tout de même possible et surtout, pour respecter la contrainte non-null de ce champ dans le formulaire d'ajout de photos du back-office (en passant, la contrainte NOT NULL correspondante n'existe pas en BDD).
Du coup, c'est un peu moche d'afficher ces dates approximatives dans le bouton de filtre et le sélecteur qui en dépend...

    **Solution proposée :** pouvoir choisir le formatage des dates affichées dans les boutons via un paramètre `comparator_date_format` dans la table `conf` de la BDD. Avec la valeur ``year`` on affiche la date au format ``YYYY``. Avec ``month`` --> ``MM/YYYY``.
Le comportement par défaut reste l'affichage de la date complète au format "day" --> ``DD/MM/YYYY`` (si paramètre non-renseigné). Ce paramètre permet aussi de filtrer en conséquence les pas de temps disponibles dans le bouton ad-hoc (exemple : si ``month`` est défini, les pas de temps disponibles seront ``1 mois`` et ``1 an``). Utile dans le cas où les dates de photos sont parfois imprécises (photos ancienns, cartes postales...).
Voir commit 6c2ed78796a818eac96e3fa30257274704acfa70 

Ce n'est probablement pas parfait voire perfectible niveau code mais cela reste assez simple et ajoute de la généricité au comparateur je trouve.

Qu'en pensez vous ?

**Comment by camillemonchicourt** [comment]
Merci pour le paramètre masquant le selecteur de pas. En effet ce besoin avait été identifié pour les OPP classiques : https://github.com/PnX-SI/GeoPaysages/issues/77#issuecomment-707170805

OK aussi sur le filtre de date, qui est pas idéal et cela avait été identifié aussi : https://github.com/PnX-SI/GeoPaysages/issues/77#issuecomment-690305886
Donc super de pouvoir le masquer avec le paramètre que tu as ajouté.

Concernant le 3° point, en effet les histoires de date, les noms des champs et les contraintes ne sont pas idéaux selon moi. A améliorer, mais en attendant ta proposition de paramètre est intéressante.

Merci pour cette PR qui permet de mieux pouvoir utiliser et alléger le comparateur V2.
@20cents, je te laisse regarder la PR dont plusieurs commits correspondaient à des choses à réaliser. Merci d'avance.

**Comment by xavyeah39** [comment]
Cool si cela peut convenir en attendant. 
Effectivement perfectible sur le 3e point. A creuser par la suite.

NB : je n'ai pas encore fais la PR en attendant des retours. 
Ces propositions sont regroupées sur mon fork dans ma branche [pnrp_dev_comparatorv2](https://github.com/xavyeah39/GeoPaysages/commits/pnrp_dev_comparatorv2) (3 derniers commits).
Si cela vous convient pour un merge faites-moi signe et je publierai une PR ;)

**Comment by camillemonchicourt** [comment]
Oui oui fais une PR si possible.
Merci.

**Comment by xavyeah39** [comment]
Fait avec #103
