### ISSUE TITLE
Carte des sites - Pouvoir ajouter le champ "référence" dans la pop-up

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoPaysages#105]
Suite aux discussions entre différents PNR et avec @geobrun, on trouvait utile de pouvoir afficher la valeur du champ "référence" d'un site (`ref_site`) dans la pop-up qui s'affiche au survol dans la carte "Sites d'observation".
En plus du nom du site et de la commune et comme c'est le cas dans la liste des sites de la sidebar.

Comme ce champ n'est pas renseigné obligatoirement voire pas utilisé du tout par certains, je vous propose de le faire avec un paramètre dans la table magique `geopaysages.conf`.
Si ce paramètre `map_popup_ref_site` est renseigné avec la valeur `True`, le champ `ref_site` s'affichera. 
Sinon, on reste sur nom du site + nom de la commune.

Qu'en pensez-vous ? intéressé par une PR ?
C'est tout prêt dans ce commit sur mon fork : 0426a8586af53f195f1be03d5594ceb6c4213c26
;)

**Comment by camillemonchicourt** [comment]
A force ça risque des paramètres pour tout et en faire des tonnes.

Pour ce cas du coup je privilégierai d'afficher la valeur du champs si elle est renseigné.
Et pas afficher si le champs est nul.
Ça fait un paramètre de moins. 😀

**Comment by xavyeah39** [comment]
Tu as raison. Beaucoup plus simple de faire comme cela et ça fait 1 paramètre de moins : 
`ref_site` ne s'affiche dans la pop-up que si sa valeur n'est pas NULL ou '' (chaîne vide).
j'ai modifié ça avec 943418af27cfed0bc76eda2f5dfd02a120c12316 sur mon fork.

Pour autant, je ne trouve pas gênant que les paramètres puissent devenir nombreux si cela donne de la souplesse et facilite la personnalisation de l'appli. D'autant plus que c'est une table qui ne compte actuellement pas plus d'une dizaine de lignes et qui à l'avantage d'être très simple à gérer par rapport à un fichier de conf + recompiler.

Mais effectivement, lorsqu’on peut éviter de créer des paramètres ou faire en sorte qu'il ne soit pas indispensable à renseigner, c'est à privilégier 😀

**Comment by xavyeah39** [comment]
fait avec 31da9b96892f2927b15d8daa4b38e091136c91df
