### ISSUE TITLE
Cartes des sites - Affichage de la photo principale dans la popup

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoPaysages#106]
En intégrant nos données dans mon instance de dev/tests, je constate un comportement qui m’interroge et qui diffère de celui des autres pages : 
La vignette de la photo affichée dans la pop-up des sites n'est pas celle définie comme principale (chez nous, la photo la plus ancienne par exemple) comme c'est le cas dans les blocs de la page d'accueil ou dans la page galerie.

Actuellement la vignette affichée est la dernière ajoutée dans une liste des photos de chaque site si je comprend bien : 
https://github.com/PnX-SI/GeoPaysages/blob/dev/backend/static/js/sites.js#L182

En théorie, la photo affichée en vignette serait donc la dernière ajoutée.
Mais dans mon cas, les photos n'ont pas forcément été ajoutées à leurs sites en allant de la plus ancienne à la plus récente. Du coup la photo qui s'affiche dans la popup est assez aléatoire parmi celles de la série...

Je serais d'avis à reproduire dans la pop-up le comportement des autres pages où l'on affiche la photo définie comme principale. Celle défini dans le champ `main_photo` de la table `t_site` (en BDD) ou via le back-office dans le champ "afficher dans la galerie" (formulaire d'ajout/modif de photos).

Qu'en pensez-vous ?
Testé et fonctionnel chez moi avec 8403f171d550a0729af140dc54a9cd0068a3346f

**Comment by camillemonchicourt** [comment]
Oui il faut que ce soit homogène et utiliser la photo pricnipale.

**Comment by geobrun** [comment]
Bonne idée effectivement ! :)

**Comment by xavyeah39** [comment]
fait avec 93b3b9c82a3573882a0e98d848b68516ed6be460  et 3311525e43e5d393a8b995ace5b78e1d320f4ac8
