### ISSUE TITLE
Passage en HTTPS

### ISSUE THREAD

**Issue by geobrun** [PnX-SI/GeoPaysages#125]
Bonjour,

Pour information, j'ai passé notre OPP en HTTPS avec Let's Ecncrypt. Cela fonctionne bien pour la partie publique. Par contre, cela génère une erreur dans la partie "admin" et empêche de se logger. A priori, cela vient du fichier "main.3751e5408dcdb328be42.js" situé dans le répertoire "app_admin". Dans ce fichier, à trois endroits, il était inscrit en dur :

- http://adresseipduserveur/api/
- http://adresseipduserveur/pictures/
- http://adresseipduserveur/static/custom/

Je suppose que l'adresse IP du serveur avec la mention HTTP a été auto-générée lors de l'installation initiale, étant donné que j'avais rentré cette information lors de l'installation (et non le nom de domaine avec la mention HTTPS).

Du coup, dans le fichier JS, j'ai remplacé "http://adresseipduserveur" par "https://domaine". Après cette modification, l'interface administrateur a l'air de fonctionner normalement, en mode sécurisé.

En espérant que cette information puisse servir à quelqu'un, voire éventuellement à apporter une correction par la suite !

**Comment by camillemonchicourt** [comment]
Merci pour cette info.
Il faudrait pouvoir modifier l'URL de l'application plus simplement.

A améliorer donc.

**Comment by geobrun** [comment]
Je suis revenu sur ce souci lors d'une réinstallation. En fait, le plus simple est sûrement de redéployer le backoffice en spécifiant une URL du type "https://domaine.fr" dans le fichier `front-backOffice/src/app/config.ts` (au lieu de l'adresse IP du serveur).
