### ISSUE TITLE
Passer la doc de .rst en .md

### ISSUE THREAD

**Issue by Jeje2201** [PnX-SI/GeoPaysages#132]
Bonjour,

Je travaille pour Natural Solutions (collègue de Vincent et Amine).

Je suis nouveau sur Geopaysages et j'ai cru comprendre qu'il fallait communiquer par ticket pour avoir des feux verts et bosser plutôt que de coder sans avoir de validation au préalable.

Passer la doc en md nous permettrai d'avoir un format de fichier homogène avec les autres docs et plus simple à maintenir

Etes-vous ok pour que je vous fasse une pull requests ?

**Comment by camillemonchicourt** [comment]
Oui on avait fait du .RST initialement car on avait l'habitude de ce format dans d'autres projets.
Mais .MD est bien aussi, voire plus simple et homogène donc pas de soucis.

Et en effet, il est souhaitable d'avoir des issues pour chaque développements, avec une PR associée pour bien suivre les développements et le projet.

Merci.

**Comment by Jeje2201** [comment]
Pull request crée : https://github.com/PnX-SI/GeoPaysages/pull/133
