### ISSUE TITLE
Instance multi-observatoires

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoPaysages#154]
Les PNR de PACA travaillent sur des évolutions de GeoPaysages pour gérer leur contexte avec une seule instance communes de GeoPaysages pour tous les PNR.
Pour cela, ils font développer la possibilité d'avoir plusieurs observatoires dans une instance.
Chaque site sera alors associée à un observatoire.
Pour les instances classiques, ils n'auront qu'un seul observatoire. 
Quand une instance n'aura qu'un seul observatoire, GeoPaysages ne fera pas remonter de mentions ou de filtre à l'observatoire.

Pour cela, une table des observatoires a été ajoutée dans la BDD.
Dans l'Admin un nouvel onglet permet de gérer les observatoires : 

![Capture d’écran de 2022-07-11 10-46-46](https://user-images.githubusercontent.com/4418840/178225298-b9d505b8-ea6a-4713-aac5-b34ccebf2de9.png)

Un observatoire comprend un nom, une référence, une couleur, une photo, une icône, une limite géographique : 

![Capture d’écran de 2022-07-11 10-46-56](https://user-images.githubusercontent.com/4418840/178225452-2bcbc3ee-f029-4e3c-8ecd-ed3c4945eaa3.png)

La page des sites a été revue pour grouper les sites par observatoire, quand l'instance en a plusieurs, éventuellement les filtrer par observatoire : 

![Capture d’écran de 2022-07-11 10-48-56](https://user-images.githubusercontent.com/4418840/178225688-0dd9a426-7e2b-479e-8c1c-2fd176e3ce0f.png)

D'autres évolutions, ajustements sont réalisés à cette occasion, comme la disposition horizontale des filtres, l'association possible d'un picto par thème pour les afficher sur la carte...

**Comment by geobrun** [comment]
La fonctionnalité "multi-observatoire" pourrait aussi nous intéresser car notre chargée de mission "paysage" pensait au départ découper notre observatoire en plusieurs petits observatoires locaux. A voir !

**Comment by camillemonchicourt** [comment]
Oui cela le permettra aussi.
Si le territoire est le même pour les différents observatoires, la limite géographique et la couleur de chaque observatoire sont optionnels. 
Si ils ne sont pas fournis, ils ne seront pas affichés et une couleur par défaut sera utilisée.

**Comment by camillemonchicourt** [comment]
Oui OK, autant harmoniser et simplifier, d'autant plus que Roboto est bien opensource donc fonctionne comme police par défaut (https://opensource.googleblog.com/2015/05/roboto-googles-signature-font-is-now.html).

Et en effet, libre ensuite à chacun d'utiliser d'autres polices.

Merci.

**Comment by Lilya-NS** [comment]
Hello, 

Sur une fiche site comme sur l'OPP du Pilat on a un champ "analyse paysagère", ce dernier correspond au champ témoignage : https://paysages.parc-naturel-pilat.fr/sites/17

Est-ce que l'on peut renomer "témoignage" en "analyse paysagère" pour tout le monde ? 
Sachant que l'OPP de la Vanoise s'en sert pour ce qui semble être une analyse paysagère : http://paysages.vanoise-parcnational.fr/comparator/2
@Chrispnv est-ce que vous confirmez ? 

Merci,
Lilya

**Comment by camillemonchicourt** [comment]
OK à creuser en effet.
"Témoignage" n'a en effet pas trop de sens et me semble peu clair et compréhensible.
Par contre "Analyse paysagère" me semble pas non plus très clair et compréhensible par tous.

Il faudrait voir ce que l'on souhaite indiquer dans ce champs et vérifier que c'est partagé et compréhensible pour le public visé, qui n'est pas un public de technicien.

**Comment by Lilya-NS** [comment]
Autre sujet : il est obligatoire d'avoir des mentions légales sur un site.
Rien n'est prévu sur GeoPaysages, la Vanoise a utiliser le copyright en pied de page en changeant le fichier de traduction pour rediriger vers leur page statique : http://paysages.vanoise-parcnational.fr/

On peut utiliser le même système que la page "about", le contenu est donc géré dans la table de conf. Ce qui voudrait dire que si le contenu est ajouté on affiche le lien et si ce n'est pas le cas non.

On pourrait placer ce lien à côté du copyright et il y aurait les informations obligatoires : https://www.economie.gouv.fr/entreprises/site-internet-mentions-obligatoires 

Merci :)

**Comment by camillemonchicourt** [comment]
Oui pour les mentions légales, c'est bien comme tu proposes.

**Comment by xavyeah39** [comment]
> Je suis totalement d'accord avec ça ! @xavyeah39 qu'en penses tu ?

Oui ça me va aussi. "Analyse paysagère" était propre à notre contexte mais on peut adopter un intitulé plus générique (que l'on peut toujours adapter avec les variables de traduction).
On peut renommer le champ "témoignage" par "description" et le champ "description" actuel par "présentation" ?

**Comment by camillemonchicourt** [comment]
Hum, pas évident de trouver les bons termes.
Je sais pas si les gens capteront la différence entre "Présentation" et "Description", et quoi mettre dans quel champs.
Moi-même je ne suis pas certain de voir la différence, et ce que je vais trouver dans l'un ou l'autre. 🤔

**Comment by Lilya-NS** [comment]
> Oui ça me va aussi. "Analyse paysagère" était propre à notre contexte mais on peut adopter un intitulé plus générique (que l'on peut toujours adapter avec les variables de traduction). On peut renommer le champ "témoignage" par "description" et le champ "description" actuel par "présentation" ?

Juste présentation et description ? La différence n'est pas très explicite... 
Présentation générale du site ? 
Description technique du site ?

**Comment by Lilya-NS** [comment]
> Hum, pas évident de trouver les bons termes. Je sais pas si les gens capteront la différence entre "Présentation" et "Description", et quoi mettre dans quel champs. Moi-même je ne suis pas certain de voir la différence, et ce que je vais trouver dans l'un ou l'autre. 🤔

Je confirme que pour moi non plus la différence n'est pas vraiment évidente...

**Comment by camillemonchicourt** [comment]
Le travail réalisé sur le sujet est en attente de tests dans la PR https://github.com/PnX-SI/GeoPaysages/pull/173

Et est déployé sur http://observatoire-des-paysages.pnrsud.fr

**Comment by orovellotti** [comment]
Dernière URL valide pour ce déploiement :http://paysages.pnrsud.fr/

**Comment by camillemonchicourt** [comment]
OK, la PR correspondant à ces développements est https://github.com/PnX-SI/GeoPaysages/pull/173
A relire, intégrer pour pouvoir faire la release.

PS : Il manque la mise en place du HTTPS sur http://paysages.pnrsud.fr

**Comment by Lilya-NS** [comment]
Hello, 

Pour le https c'est en cours de leur côté oui !

**Comment by xavyeah39** [comment]
OK avec la release de la [v1.3.0](https://github.com/PnX-SI/GeoPaysages/releases/tag/v1.3.0)
