### ISSUE TITLE
Suppression du block jinja header_title

### ISSUE THREAD

**Issue by 20cents** [PnX-SI/GeoPaysages#156]
Le template jinja layout.html contient un block header_title pensé à la base pour afficher le titre de la page.
Il s'avère qu'il ne sert que pour l’accueil et la fiche site, et dans ces 2 cas il est utilisé très différemment.
Je voudrais le supprimer mais il y a aura une petite note de release à suivre.
OK ?

**Comment by camillemonchicourt** [comment]
Ouais OK, si c'est bien indiqué dans les notes de version (https://github.com/PnX-SI/GeoPaysages/blob/master/docs/changelog.rst)

**Comment by xavyeah39** [comment]
Fait dans la [v1.3.0](https://github.com/PnX-SI/GeoPaysages/releases/tag/v1.3.0)
