### ISSUE TITLE
Stockage des blocks de home et des pages en fichier jinja plutôt qu'en DB

### ISSUE THREAD

**Issue by 20cents** [PnX-SI/GeoPaysages#158]
L'app propose au diffuseur de l'instance un block d'intro en page d'accueil.
(La prochaine version proposera en plus un 2ème block)
Le contenue de ce block est actuellement stocké en base, on préférerai l'implémenter en jinja.
Avantages :
- Bénéficier des fonctionnalités jinja
- Accès à des fonctions custom écrites en python (donc accès à la DB, aux variables d'env, etc...)
- Versionnable donc plus facilement livrable pour un presta

Je propose aussi de faire pareil pour les pages stockées en base

**Comment by camillemonchicourt** [comment]
Oui je suis pas fans des contenus de pages stockés dans la BDD.

Mais je ne vois pas à quoi correspond le fait de les stocker en jinja ?

Cela prend quelle forme ?
Des pages HTML ?

**Comment by 20cents** [comment]
Ce serait un peu la même chose que les fichiers du dossier backend/tpl. Ils seraient dans un dossier hors du dépôt Geopaysage pour être versionnés dans un autre dépôt.
Il y aurait aussi un .py pour mettre les fonctions et routes custom.

**Comment by camillemonchicourt** [comment]
OK, il faut quand même que ça reste simple pour des utilisateurs qui connaissent juste le HTML et CSS.

Et sinon, je suis pas trop emballé par le fait d'avoir un autre dépôt pour cela.

On ne peut pas juste fournir des fichiers des fichiers .sample et gitignorer les versions modifiées de chaque customisation ?

**Comment by 20cents** [comment]
Oui ce sera simple car l'utilisateur peut faire juste du html-css-js (comme xavier avec son bandeau d'images), le jinja c'est du bonus.
On est pas obligé d'avoir un dépôt, il faut juste rassembler tous les éléments de customisation dans un dossier pour qu'on puisse le versionner si besoin. Un dossier gitignorer peut lui-même contenir un .git et donc être lié à un dépôt.
Pour nous qui réalisons, entre autre, une presta de customisation c'est important que notre job soit versionné :
- travaille collaboratif
- historisation du job
- déploiement sur les instance de dev, demo, prod.
