### ISSUE TITLE
Problème avec le fichier messages.po

### ISSUE THREAD

**Issue by geobrun** [PnX-SI/GeoPaysages#161]
Bonjour tout le monde,

J'ai procédé à une nouvelle installation de GeoPaysages 1.2.1 sur un serveur Debian 10 (comme spécifié dans la doc). J'ai modifié les textes du site via le fichier `messages.po` comme je le faisais avant, en compilant ce fichier modifié avec la commande venv `pybabel compile -d i18n`. A priori, la compilation se passe bien car le fichier résultant `messages.mo` contient bien les textes que j'ai mis  jour. Par contre, côté site internet, rien ne se passe !

On dirait que le nouveau fichier `messages.po` n'est pas utilisé par le site et que ce dernier garde quelque part la précédente version de ce fichier (je ne sais pas comment fonctionne exactement l'architecture de GeoPaysages à ce niveau). Est-ce que quelqu'un a une idée où je pourrais chercher la cause de ce problème ? J'ai procédé à plusieurs installations, le problème se reproduit à chaque fois.

**Comment by geobrun** [comment]
En fouinant un peu plus, je me rentre compte que la modification des fichiers HTML se trouvant dans le dossier `backend/tpl` (comme `home.html` par exemple) ne fonctionne pas non plus. Pourtant, je lance bien la commande `sudo service supervisor restart` après chaque modification, comme indiqué dans la doc. Cela donne du coup l'impression que c'est au niveau de la "compilation" des mises à jour (HTML ou babel) qu'il y a un souci.

**Comment by geobrun** [comment]
Ok, problème résolu, j'avais un second supervisor de lancé en même temps qui bloquait le supervisor de GeoPaysages... (cf. la réponse de [N'faly Kaba](https://stackoverflow.com/questions/25121838/supervisor-on-debian-wheezy-another-program-is-already-listening-on-a-port-that))

**Comment by camillemonchicourt** [comment]
Merci pour ce retour.
