### ISSUE TITLE
Mise à jour applicative - Pb MAJ v1.0.1dev0 vers 1.2.1

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/GeoPaysages#168]
Bonjour,

Depuis le développement effectué par Natural Solutions, donc en version 1.0.1dev0, l'application Geopaysage n'a jamais été mise à jour.
J'ai suivi la doc pour la mettre à jour vers la version 1.2.1. J'ai regardé si des versions intermédiaires devaient être installées. Ce n'est pas le cas à priori.
J'ai une erreur 502 Bad Gateway.
Une idée de l'erreur. Une commande non lancée ? Une config mal implémentée (j'ai vérifié) ?
Merci de votre aide.

**Comment by geobrun** [comment]
Bonjour,

Nous sommes nous-mêmes passés en septembre dernier de la version 1.0.1 à la version 1.2.1. Malheureusement, nous ne sommes pas passés par la procédure de mise à jour : nous avons tout réinstallé de A à Z, en réimportant les données dans la nouvelle base.

Si tu as plus de détails, je peux regarder s'il y a une différence quelque part avec l'installation sur notre serveur.

**Comment by camillemonchicourt** [comment]
On a fait des mises à jour sans soucis.

Il faudrait des logs pour y voir plus clair.

**Comment by Chrispnv** [comment]
Bonjour,

Voici les erreurs que j'ai dans les logs et à l'installation. Je n'ai rien dans /var/log/geopaysages

NGINX : dans error.log
2022/12/12 11:27:48 [error] 467#467: *1068283 connect() failed (111: Connection refused) while connecting to upstream, client: 66.249.70.253, server: paysages.vanoise-parcnational.fr, requ$
2022/12/12 11:35:24 [error] 467#467: *1068285 connect() failed (111: Connection refused) while connecting to upstream, client: 62.102.224.250, server: paysages.vanoise-parcnational.fr, req$

./update_app.sh : message à la fin de l'update
Collecting GeoAlchemy2==0.5.0 (from -r ./backend/requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/5b/e2/09f9a4c17cf85f142421384550481c34571da594a49368660f26e53318e5/GeoAlchemy2-0.5.0-py2.py3-none-any.whl
Collecting inflect==4.1.0 (from -r ./backend/requirements.txt (line 12))
  Could not find a version that satisfies the requirement inflect==4.1.0 (from -r ./backend/requirements.txt (line 12)) (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.3, 0.2.4, 0.2.5, 0.3.0, 0.3.1, 1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1, 2.1.0, 3.0.1, 3.0.2)
No matching distribution found for inflect==4.1.0 (from -r ./backend/requirements.txt (line 12))
./update_app.sh: ligne 59: pybabel : commande introuvable
./update_app.sh: ligne 60: pybabel : commande introuvable
./update_app.sh: ligne 61: pybabel : commande introuvable
Restart
Backup prev backoffice to app_admin-v1.2.1

**Comment by camillemonchicourt** [comment]
L'erreur sur "pybabel" semble indiquer un soucis avec les fichiers de traduction.
Dans votre surcouche de traduction ?

**Comment by Lilya-NS** [comment]
Pour information, nous avons commencé à accompagner Christophe dans la mise à jour de son instance.
Mais il faut d'abord un serveur à jour pour installer Docker.

**Comment by xavyeah39** [comment]
Les procédures d'[installation](https://github.com/PnX-SI/GeoPaysages/blob/master/docs/installation.md) et de [mise à jour](https://github.com/PnX-SI/GeoPaysages/blob/master/docs/mise_a_jour.md) ont été entièrement revues et simplifiées avec la [v1.3.0](https://github.com/PnX-SI/GeoPaysages/releases/tag/v1.3.0).
Docker est désormais utilisé ce qui facilite le déploiement et les màj mais demande de suivre une petite [procédure de migration](https://github.com/PnX-SI/GeoPaysages/blob/master/docs/migration_v1.2_to_v1.3.md) depuis la version 1.2 ou antérieure.

Réouvrir si nécessaire.
