### ISSUE TITLE
disponible dans plusieurs langues

### ISSUE THREAD

**Issue by vajapavlovic** [PnX-SI/GeoPaysages#184]
Nous avons un client qui souhaite disposer de GeoPaysage en deux langues : français et allemand.

**Comment by 20cents** [comment]
Navré, le multilingue n'est pas implémenter, on s'est servit des fichiers de traductions pour simplifier la personnalisation des textes de l'app. Je pense qu'il y a un grand pas à franchir.  

La 1ère étape est assez simple, prendre en charge de la langue via l'url :
- Pour bien faire `domain.com/<lang>/ma_page`
- Pour faire simple `domain.com/ma_page?lang=<lang>` (Il me semble que ça pose des problèmes de référencement)
 
Ensuite il faut pouvoir traduire tous les contenues stockés en DB : (Observatoires, Points d'observations, Thématiques, etc...)
- Adapter le modèle de données
- Adapter l'admin pour pouvoir saisir les traductions de chaque champ texte existant.

**Comment by camillemonchicourt** [comment]
OK, je suis étonné car c'était ce qui était prévu et que le ticket https://github.com/PnX-SI/GeoPaysages/issues/3 laissait penser que c'était OK. 🤔

**Comment by camillemonchicourt** [comment]
Ticket dupliqué : https://github.com/PnX-SI/GeoPaysages/issues/3
