### ISSUE TITLE
UsersHub-authentification-module

### ISSUE THREAD

**Issue by HamoudaAmine** [PnX-SI/GeoPaysages#4]
Quelle version de UsersHub-authentification-module doit-on utiliser ?
La version master ne correspond pas aux inserts fournis par le parc national de la Vanoise

1-  _"### POST /api/auth/login HTTP/1.1" 500 -
(psycopg2.ProgrammingError) ERREUR: la colonne v_userslist_forall_applications.pass_plus n'existe pas
LINE 1: ...tilisateurs_v_userslist_forall_applications_pass, utilisateu…_

2- _### ERREUR: la colonne t_applications.id_parent n'existe pas
LINE 3: WHERE utilisateurs.t_applications.id_parent = '10' AND utili…_

**Comment by camillemonchicourt** [comment]
Oui on vient justement d'apporter des précisions à la doc dans la branche ``develop``.
Voir https://github.com/PnX-SI/UsersHub-authentification-module/issues/2#issuecomment-436993110

La dernière version du module fonctionne bien mais il ne faut pas utiliser le SQL local, mais bien celui du dépôt UsersHub. 

Il faut qu'on fasse quelques tests avant de faire une nouvelle release mais vous pouvez utiliser la branche ``develop`` pour le moment : https://github.com/PnX-SI/UsersHub-authentification-module/compare/develop

**Comment by Chrispnv** [comment]
Bonjour,

Je pense que l'on va un peu vite en besogne sur cette application 
GeoPaysage qui est chez nous un observatoire photographique des 
paysages. Le développement n'est pas encore terminé par le prestataire, 
donc entre ce qu'on trouve sur Github actuellement et ce qui sera en 
production, il y a encore un fossé. On travaillera sur la mise à 
disposition de l'outil en lien avec usershub sur Github une fois la 
prestation effectuée, testée...

Merci de votre compréhension.

Untitled Document
------------------------------------------------------------------------
		Christophe CHILLET
Responsable de l'unité Système d'information

Parc national de la Vanoise
Tél : +33(0)4 79 62 90 16 - Fax : +33 (0)4 79 96 37 18
www.vanoise-parcnational.fr <http://www.vanoise-parcnational.fr/>
rando.vanoise.com <http://rando.vanoise.com/fr/>

<https://www.facebook.com/parcnationaldelavanoise> 
<https://twitter.com/pnvanoise> 
<https://www.youtube.com/user/ParcNationalVanoise>
		Faites un geste pour l'environnement : n'imprimez ce message qu'en cas 
de nécessité

Le 13/11/2018 à 14:38, HamoudaAmine a écrit :

**Comment by camillemonchicourt** [comment]
Je ne comprends pas de quoi tu parles ?
La CCTP indique que l'application doit permettre de se connecter avec UsersHub donc là on parle de la connexion au module qui permet cela.
