### ISSUE TITLE
Problème install_db.sh

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoPaysages#46]
L'utilisateur ``oppvuser`` est en dur dans le fichier https://github.com/PnX-SI/GeoPaysages/blob/master/install_configuration/oppvdb.sql
du coup si on change l'utilisateur de BDD dans le ``settings.ini``, le script ne fonctionne pas.

**Comment by camillemonchicourt** [comment]
Oui.
Normalement on devrait installer la BDD avec l'utilisateur admin.
Puis faire un Grant Select à l'utilisateur user qui est utilisé pour lire le contenu uniquement.

**Comment by HamoudaAmine** [comment]
@Chrispnv non il ne faut pas créer les utilisateurs avant de lancer le scripte install_db.sh
le scripte va les créer à partir du fichier settings.ini

**Comment by HamoudaAmine** [comment]
@TheoLechemia @camillemonchicourt  j'ai enlevé l’utilisateur oppvuser qui était en dur le fichier sql
