### ISSUE TITLE
Problème supervisorctl

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/GeoPaysages#47]
Quelques petits retour du test d'install:

- les repertoires de log ``/var/log/oppv_vanoise/`` ne sont pas créer lors de l'install_app. Du coup tel quel, le lancement du supervisor ne fonctionne pas.

- la commande que doit lancer le supervisor pour lancer gunicorn ne fonctionne pas chez moi: 
```
directory=/home/demogeonature/geopaysages/backend
command=/home/demogeonature/venv/bin/gunicorn app:app -b localhost:8001
autostart=true
autorestart=true
```
Si je lance ``/home/demogeonature/venv/bin/gunicorn app:app -b localhost:8001`` à la main, j'ai cette erreur :`/home/demogeonature/venv/bin/gunicorn app:app -b localhost:8001` (mon venv est bien créé et mon chemin est correct).

J'ai essayé de lancé le serveur en mode dev (FLASK_APP=./app.py FLASK_DEBUG=1 flask run), il se lance correctement, mais j'ai une timeout sur mon navigateur.

**Comment by camillemonchicourt** [comment]
L'installation fonctionne bien désormais, confirmée en 1.0.0-rc.3.7, mais je ne suis pas sur que tous les points indiqués ci-dessus sont réglés ?
