### ISSUE TITLE
ADMIN - Mask partiel

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoPaysages#61]
Quand on saisit sur un écran moyen (PC portable par exemple) et qu'on enregistre, le Mask de chargement ne s'affiche que sur la partie haute de la page donc on ne le voit pas forcément : 

![image](https://user-images.githubusercontent.com/4418840/57929441-9ec99180-78b3-11e9-84e6-cc00dab243b3.png)

Une alternative à cela serait que la page fasse globalement 100% de haut, sans scroll. 
Avec une carte qui ferait 100% de haut et serait fixe (``max-height:70vh`` sur ``col-map``) et idem pour le formulaire dans lequel on scrolle (``overflow-y: auto;max-height: 85vh;`` sur ``col-table``). Cela faciliterait aussi l'ergonomie globale de la saisie : 

![image](https://user-images.githubusercontent.com/4418840/57929735-6a0a0a00-78b4-11e9-8c98-704c768314a3.png)

**Comment by xavyeah39** [comment]
Semble corrigé. 
Pas reproduit en 1.0.0rc4.2

**Comment by xavyeah39** [comment]
Non reproduit en [v1.3.0](https://github.com/PnX-SI/GeoPaysages/releases/tag/v1.3.0)
