### ISSUE TITLE
Vue en mode développement

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoPaysages#63]
J'ai installé GeoPaysages de manière standard mais la console indique : 
```
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
```

Je ne suis pas sur que cela soit souhaitable désormais ?

**Comment by 20cents** [comment]
Bien vu

**Comment by camillemonchicourt** [comment]
Should be fixed by https://github.com/PnX-SI/GeoPaysages/commit/b722b33ba944669fc7158038d09159cd8ce031bf

**Comment by camillemonchicourt** [comment]
Fixed in version 1.0.0-rc.4
