### ISSUE TITLE
Texte et page de présentation

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoPaysages#65]
Il semblerait qu'aucune zone ou page ne soit prévue pour présenter le portail, la démarche, le contexte. Assez brut et déconcertant du coup. Et peu explicite. 

Il faudrait prévoir à minima : 
- Un bloc HTML sur la home surcouchable et désactivable permettant de présenter le portail, le projet
- Une page de présentation HTML surcouchable permettant d'aller plus loin dans la présentation. 

Sur le modèle de ce qui a été fait dans GeoNature-atlas par exemple

**Comment by camillemonchicourt** [comment]
Bloc HTML sous le bloc de photo, où les gens mettent ce qu'ils veulent en HTML avec les classes Bootstrap et la surcouche CSS si besoin.
Un template HTML par langue ou dans les fichiers de traductions ?
Bien récupérer cette customisation à chaque mise à jour.

**Comment by 20cents** [comment]
Demo du texte d'intro sur la home :
http://vps587786.ovh.net/
Je l'ai stocké en bdd dans la table de conf, il me semble que c'est plus simple pour l'administrer.
On pourrait un jour avoir un éditeur dans l'admin.
La table de conf est key:value
D'abord on regarde s'il y a home_intro_<lang> sinon juste home_intro sinon rien

**Comment by camillemonchicourt** [comment]
OK, merci pour cette solution technique. Pas le plus simple à éditer si on met un long texte avec de la mise en forme, voire des images etc, notamment pour la page de présentation. Mais ça permet d'être plus générique, multilangue et d'envisager de gérer le contenu dans l'Admin plus tard.
OK donc pour moi comme fonctionnement. Je me demande juste pourquoi le code fait référence en dur à ``home_intro_fr`` si le système de langue est générique ? On n'est pas forcément en français.

J'aurai plutôt mis le texte d'introduction avant la mosaïque des images. Mais pas forcément évident pour tous ?
En faire un paramètre pour le avant ou après ?
Ou sinon on le met plutôt avant et on verra à l'usage ?

Pour la page de présentation, je me demande si on la nomme "Présentation" (presentation_page) ou plutôt "A propos" (about_page) ?

**Comment by geobrun** [comment]
Je suis de loin vos discussions. Si ça peut intéresser, de mon côté, j’ai mis un texte d’introduction directement dans la mosaïque à la place d’une image. Il est stocké dans le fichier d’internationalisation « messages.po ».
http://opp-paysage.pnr-millevaches.fr/

Ce n’est pas optimal pour s’adapter à tout type d’écran (notamment les plus petits), mais ça marche plutôt bien sur des écrans standards.

P.S. : le site est encore en construction, ne pas diffuser


[cid:image002.png@01D68082.C7F081E0]<http://www.pnr-millevaches.fr/>


Geoffrey BRUN
Chargé de mission Géomatique
g.brun@pnr-millevaches.fr<mailto:g.brun@pnr-millevaches.fr>
Ligne directe : 05 55 96 97 18
Standard : 05 55 96 97 00

Syndicat mixte d’aménagement et de gestion du

Parc naturel régional de Millevaches en Limousin
Maison du Parc – 7 route d’Aubusson – 19290 Millevaches
[cid:image003.png@01D68082.C7F081E0]<http://www.pnr-millevaches.fr/>
Ensemble, respectons l’environnement, merci de n’imprimer ce mail que si c’est nécessaire.
















De : Camille Monchicourt [mailto:notifications@github.com]
Envoyé : mardi 1 septembre 2020 17:03
À : PnX-SI/GeoPaysages
Cc : Subscribed
Objet : Re: [PnX-SI/GeoPaysages] Texte et page de présentation (#65)


OK, merci pour cette solution technique. Pas le plus simple à éditer si on met un long texte avec de la mise en forme, voire des images etc, notamment pour la page de présentation. Mais ça permet d'être plus générique, multilangue et d'envisager de gérer le contenu dans l'Admin plus tard.
OK donc pour moi comme fonctionnement. Je me demande juste pourquoi le code fait référence en dur à home_intro_fr si le système de langue est générique ? On n'est pas forcément en français.

J'aurai plutôt mis le texte d'introduction avant la mosaïque des images. Mais pas forcément évident pour tous ?
En faire un paramètre pour le avant ou après ?
Ou sinon on le met plutôt avant et on verra à l'usage ?

Pour la page de présentation, je me demande si on la nomme "Présentation" (presentation_page) ou plutôt "A propos" (about_page) ?

**Comment by camillemonchicourt** [comment]
Ah super, merci pour le lien et ravi que vous ayez pu déployer l'outil. Une version 1.1.0 est en préparation comme tu as du le comprendre (https://github.com/PnX-SI/GeoPaysages/projects/1).  

L'idée de le mettre dans la mosaïque est intéressante.
Mais comme on vise un truc générique, pas sur que ça s'adapte bien à tous les cas. 
Donc je resterai sur un bloc avant ou après la mosaïque pour commencer, et à voir si on peut faire plus complexe ensuite ?

**Comment by geobrun** [comment]
Effectivement, la solution que je propose peut être problématique car si quelqu'un veut mettre un long pavé dans le bloc de texte, cela va vite devenir illisible (trop petit) !

**Comment by camillemonchicourt** [comment]
Oui et en l'état cela ne fonctionne pas sur mobile.
Mais ça me semble une piste intéressante à creuser pour une évolution prochaine.

**Comment by geobrun** [comment]
Effectivement, je n'ai pas encore programmer la partie mobile. Je fera ça prochainement, ça ne devrait pas être compliqué à faire. Je suis parti du principe que la partie mobile n'était pas prioritaire pour un observatoire du paysage : des photos se regardent mieux sur un véritable ordinateur que sur un smartphone ! :)

**Comment by xavyeah39** [comment]
Salut,

De mon côté j'ai aussi opté pour l'ajout d'un paramètre en BDD dans la table `conf` pour activer (true) ou non (false) un bloc html que j'ai appelé `home_welcome_section`.

Pour ça, j'ai ajouté un bloc avec condition sur ce paramètre dans le template `home.html`, mis les blocs dans des sections et ajouté du css dans `home.css` qui s'applique sur cette nouvelle section nommée `welcome` (surcouchable dans `custom.css` du coup).

Pour les contenu de textes tout est dans le fichier d'internationalisation `messages.po` avec des variables pour le titre de bienvenue (`welcome_title`), le texte chapeau (`welcome_text`) et les autres éléments (`welcome_button` et `welcome_scroll_text`).

Le tout placé au dessus de la mosaïque avec une image de fond.

[Aperçu de ce que ça donne ici](http://paysages.parc-naturel-pilat.fr/) (idem, site en construction --> ne pas diffuser) 

Par contre, faute de temps, je ne me suis pas attaqué à : 
- l'affichage responsive sur mobile 
- essayer de le gérer avec des templates customisables (comme dans geonature-atlas)
- mettre au propre et proposer une PR  ;)

**Comment by 20cents** [comment]
@camillemonchicourt 
> Je me demande juste pourquoi le code fait référence en dur à home_intro_fr si le système de langue est générique ?

Il me semble que le code n'a pas de ref en dur à `home_intro_fr`
En revanche j'ai modifié le nom de la variable `intro_fr` pour `intro_locale` dans le template home.html

**Comment by camillemonchicourt** [comment]
@xavyeah39, la solution retenue pour le moment est pas uniquement un paramètre activant ou non le bloc dans la BDD, mais bien que tout le contenu du bloc soit dans la BDD, pour gérer aussi le multilangue, et envisager à terme de l'éditer dans l'ADMIN. Donc pas de fichier HTML custom, mais des champs dans la BDD dans ce qui a été proposé.
Le bloc est plus simple et générique, même si on peut en surcoucher le CSS dans le fichier de surcouche CSS.

@20cents, oui je parlai de la variable ``intro_fr``, merci pour le renommage.
OK pour faire pareil pour la page de présentation, nommé "A propos", donc ``about_page``. Merci.

**Comment by 20cents** [comment]
J'ai mis un param en table de conf pour la position du du texte d'intro.
Si ce param n'est pas renseigné ou que ça valeur n'est ni `top` ni `bottom` alors le texte n'apparaît pas

**Comment by xavyeah39** [comment]
@camillemonchicourt,
> @xavyeah39, la solution retenue pour le moment est pas uniquement un paramètre activant ou non le bloc dans la BDD, mais bien que tout le contenu du bloc soit dans la BDD, pour gérer aussi le multilangue, et envisager à terme de l'éditer dans l'ADMIN. Donc pas de fichier HTML custom, mais des champs dans la BDD dans ce qui a été proposé.
Le bloc est plus simple et générique, même si on peut en surcoucher le CSS dans le fichier de surcouche CSS.

OK. 
Si je comprend bien, on pourra donc directement injecter/personnaliser le HTML du bloc d'intro dans le paramètre ad-hoc de la table `conf` (plutôt que le HTML soit imposé dans le template) ? 
Si oui, top !

**Comment by camillemonchicourt** [comment]
Oui c'est ça, avec possibilité de le définir par langue.

OK pour le paramètre de position, impeccable.

Il faudrait maintenant documenter tous les paramètres disponibles et leurs valeurs.

**Comment by 20cents** [comment]
http://vps587786.ovh.net/about

**Comment by 20cents** [comment]
Désolé pour le libellé de commit pas top

**Comment by camillemonchicourt** [comment]
OK merci.
Dans ce cas, tu as mis quoi comme contenu de test dans le champs de la BDD ?

**Comment by 20cents** [comment]
J'ai mis à jour la doc :
https://github.com/PnX-SI/GeoPaysages/blob/dev/docs/installation.rst#activation-du-block-dintro-en-page-daccueil

**Comment by camillemonchicourt** [comment]
OK pour moi, merci.

**Comment by camillemonchicourt** [comment]
Dans cet exemple, le contenu du paramètre ``page_about_content`` dans la BDD est : 

```
<div class="container">
    <div class="row">
      <div class="col">
        <img src="/static/images/sample.png">
      </div>
      <div class="col">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus magna lectus, auctor nec dapibus a, sagittis
          sit amet diam. In vehicula est quam, id volutpat arcu molestie sed. Nam vestibulum tempor urna. Nulla in lectus
          et augue tempus pellentesque quis non justo. Orci varius natoque penatibus et magnis dis parturient montes,
          nascetur ridiculus mus. Etiam pharetra nisi ligula, at volutpat leo condimentum eu. Vivamus pretium blandit
          interdum.
        </p>
        <p>
          Quisque maximus vitae tortor eu dignissim. Sed sed lectus consequat, molestie dolor a, auctor nisl. Praesent
          aliquam id lacus ac congue. Nulla quis ultrices eros. Nullam efficitur nulla quis magna sollicitudin, sit amet
          placerat felis dictum. Ut eu accumsan risus, scelerisque varius augue. Curabitur eleifend in orci at
          vestibulum.
        </p>
        <p>
          Sed convallis ornare venenatis. Donec vitae molestie felis. Morbi tortor erat, ultrices sed faucibus sit amet,
          viverra at lorem. Ut a eros tempus enim euismod tempor eget ut nunc. Donec nec urna ac ipsum dapibus tempor eu
          a nibh. Cras nisi ante, congue quis pulvinar ac, feugiat nec justo. Aliquam et pharetra sem.
        </p>
        <p>
          Sed convallis ornare venenatis. Donec vitae molestie felis. Morbi tortor erat, ultrices sed faucibus sit amet,
          viverra at lorem. Ut a eros tempus enim euismod tempor eget ut nunc. Donec nec urna ac ipsum dapibus tempor eu
          a nibh. Cras nisi ante, congue quis pulvinar ac, feugiat nec justo. Aliquam et pharetra sem.
        </p>
      </div>
    </div>
  </div>
```

Le titre ``page_about_title`` est un texte qui est affiché en <h1> centré au début de la page. 
Le nom de la page ABOUT dans le MENU est défini dans les fichiers de langue.
