### ISSUE TITLE
Display_gal_photo non pris en compte ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoPaysages#66]
La valeur de ce champs ne semble pas utilisée. 
J'ai passé ce champs à TRUE pour des photos, et celles-ci n'apparaissent pas dans la Galerie photos.

**Comment by camillemonchicourt** [comment]
Should be fixed by https://github.com/PnX-SI/GeoPaysages/commit/724117d2d308a017a1c9de057a754f92188dff6c

**Comment by xavyeah39** [comment]
Semble corrigé. Pas reproduit

**Comment by xavyeah39** [comment]
Corrigé.
Lié à #60
