### ISSUE TITLE
Généricité et fichier de langue

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoPaysages#68]
Plusieurs messages des fichiers de langue sont spécifiques au PnVanoise.
Il est possible de modifier les fichiers de langue, mais les modifications seront à refaire à chaque mise à jour et dans chaque langue...
Un mécanisme avec un paramètre du nom de la structure aurait été surement plus pertinent

Il faut aussi revoir la doc car les commandes indiquées pour recompiler les fichiers de langue ne sont pas OK :  
```
geopaysages@GeoPaysages:~$ cd geopaysages/
geopaysages@GeoPaysages:~/geopaysages$ . venv/bin/activate
(venv) geopaysages@GeoPaysages:~/geopaysages$ . pybabel compile -d i18n
-bash: import : commande introuvable
-bash: import : commande introuvable
from: can't read /var/mail/babel.messages.frontend
-bash: /home/geopaysages/geopaysages/venv/bin/pybabel: ligne 10: erreur de syntaxe près du symbole inattendu « ( »
-bash: /home/geopaysages/geopaysages/venv/bin/pybabel: ligne 10: `    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])'
```

Il faut faire : 
```
(venv) geopaysages@GeoPaysages:~/geopaysages$ pybabel compile -d backend/i18n
deactivate
```

**Comment by 20cents** [comment]
Il y a un script de mise à jour qui permet de monter de version sans perdre les modifs sur les éléments personnalisables (conf, css, traductions)
Ceci dit, d'autres pratiques peuvent m'intéresser.
Mais je n'ai pas compris :
> Un mécanisme avec un paramètre du nom de la structure

**Comment by camillemonchicourt** [comment]
Oui mais du coup c'est dangereux de rapatrier le fichier de langue modifié d'une version à une autre. 
Car si des termes ont été ajoutés dans le cœur de GeoPaysages entre 2 versions, ils seront perdus en rapatriant le fichier de langue de la version précédente.

Ce que j'évoquai comme mécanisme de paramètre est d'avoir un paramètre dans la conf de GeoPaysages du type ``$structure_name = Parc national de la Vanoise``

Du coup chacun pourrait remplacer cette valeur, et ainsi pas besoin de mettre le nom de la structure en dur dans les fichiers de langue comme ici : 

https://github.com/PnX-SI/GeoPaysages/blob/master/backend/i18n/fr/LC_MESSAGES/messages.po#L125-L131

Ainsi cela n'impose pas de surcoucher les fichiers de langue, juste pour modifier le nom de la structure, mais gérer cela en dehors des fichiers de langue, avec un paramètre applicatif.

**Comment by camillemonchicourt** [comment]
Voir https://github.com/PnX-SI/GeoPaysages/releases/tag/v1.0.0-rc.4
Le script de mise à jour ajoute les nouvelles clés de traductions à celles existantes.
L'utilisateur de l'instance devra les remplir et recompiler le catalogue de traduction.
