### ISSUE TITLE
app_admin/index html?

### ISSUE THREAD

**Issue by Arnoul** [PnX-SI/GeoPaysages#69]
Je viens d'installer l'application en suivant les procédures mais je rencontre un problème avec le backoffice. Dans le fichier de conf de nginx il pointe sur le répertoire app_admin/index.html à la racine de site.
J'ai bien le répertoire mais je n'ai pas le fichier index.html qui me permet de lancer le backoffice.

**Comment by camillemonchicourt** [comment]
De mémoire, j'ai fait une installation de base en suivant la doc (https://github.com/PnX-SI/GeoPaysages/blob/master/docs/installation.rst#installation-du-back-office).

La page index.html a été générée automatiquement lors de l'installation du Backoffice, à partir de ce template : https://github.com/PnX-SI/GeoPaysages/blob/master/front-backOffice/src/index.html

Chez moi son contenu est : 

```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>GeopaysageBackOffice</title>
  <base href="/app_admin/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles.0c861990fd7e32b1c80a.css"></head>
<body>
  <app-root></app-root>
<script type="text/javascript" src="runtime.ec2944dd8b20ec099bf3.js"></script><script type="text/javascript" src="polyfills.7037a817a5bb670ed2ca.js"></script><script type="text/javascript" src="scripts.76dbb051a5fcaec9e270.js"></script><script type="text/javascript" src="main.5123fae288e7c554e7b2.js"></script></body>
</html>
```

Le dossier en question contient de nombreux fichiers : 

![image](https://user-images.githubusercontent.com/4418840/64981184-cb220880-d8bb-11e9-9d2c-82dede921d2a.png)

Tu as du avoir un problème lors de l’exécution de la commande d'installation ``./install_backoffice.sh`` (https://github.com/PnX-SI/GeoPaysages/blob/master/install_backoffice.sh)

@HamoudaAmine, une piste ?
