### ISSUE TITLE
problème avec pybabel 

### ISSUE THREAD

**Issue by Arnoul** [PnX-SI/GeoPaysages#73]
Quand je lance la commande . pybabel compile -d i18n, je rencontre un problème dans le pybabel : ci-dessous le message :

-bash: import : commande introuvable
-bash: import : commande introuvable
from: can't read /var/mail/babel.messages.frontend
-bash: /home/adminsitopp/geopaysages/venv/bin/pybabel: ligne 10: erreur de syntaxe près du symbole inattendu « ( »
-bash: /home/adminsitopp/geopaysages/venv/bin/pybabel: ligne 10: `    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sy                               s.argv[0])'

**Comment by Arnoul** [comment]
et ca aussi : 
-bash: erreur de syntaxe près du symbole inattendu « ( »

**Comment by camillemonchicourt** [comment]
Oui j'avais réussi à modifier les fichiers de langue pour remplacer "Parc national de la Vanoise" notamment. Mais désormais quand je suis la procédure (https://github.com/PnX-SI/GeoPaysages/blob/master/docs/installation.rst#internationalisation-de-lapplication), j'ai aussi une erreur : 

```sh
geopaysages@GeoPaysages:~$ cd geopaysages/
geopaysages@GeoPaysages:~/geopaysages$ . venv/bin/activate
(venv) geopaysages@GeoPaysages:~/geopaysages$ cd backend/i18n/
(venv) geopaysages@GeoPaysages:~/geopaysages/backend/i18n$ . pybabel compile -d i18n
-bash: import : commande introuvable
-bash: import : commande introuvable
from: can't read /var/mail/babel.messages.frontend
-bash: /home/geopaysages/geopaysages/venv/bin/pybabel: ligne 10: erreur de syntaxe prÃ¨s du symbole inattendu Â« ( Â»
-bash: /home/geopaysages/geopaysages/venv/bin/pybabel: ligne 10: `    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sy                          s.argv[0])'
(venv) geopaysages@GeoPaysages:~/geopaysages/backend/i18n$
```

Peut-être car le chemin n'est pas le bon chemin car la doc indique ``backend/i18n/fr/messages.po`` alors que le fichier est dans ``backend/i18n/fr/LC_MESSAGES/messages.po`` ?

Je suis encore en v1.0.0-rc.3.7.

**Comment by 20cents** [comment]
Je pense qu'on a mal documenté la commande `$ pybabel compile -d i18n`
On dit qu'il faut la lancer depuis le dossier i18n
Mais l'option `-d i18n` indique que le dossier racine est i18n
Et biensûr, il n'y a pas de dossier i18n dans le dossier i18n :-)
Donc, essayer au choix :
- de spécifier l'option `-d .`
- de ne pas spécifier l'option -d
- ou même de lancer la commande depuis le répertoire parent

On corrigera la doc selon l'option choisie.

**Comment by camillemonchicourt** [comment]
OK ! En effet comme ça ça fonctionne et il ne faut pas mettre le . au début de la commande aussi à priori : 

```sh
geopaysages@GeoPaysages:~$ cd geopaysages/
geopaysages@GeoPaysages:~/geopaysages$ . venv/bin/activate
(venv) geopaysages@GeoPaysages:~/geopaysages$ cd backend/
(venv) geopaysages@GeoPaysages:~/geopaysages/backend$ pybabel compile -d i18n
compiling catalog i18n/fr/LC_MESSAGES/messages.po to i18n/fr/LC_MESSAGES/messages.mo
```
