### ISSUE TITLE
Problème à l'enregistrement dune fiche avec 2 photos

### ISSUE THREAD

**Issue by Arnoul** [PnX-SI/GeoPaysages#74]
Impossible d'enregistrer un site si plus d'une photo. A partir de deux photos, au moment d'enregistrer j'ai un message "Une erreur est survenue sur le serveur".

**Comment by xavyeah39** [comment]
Non reproduit en [v1.3.0](https://github.com/PnX-SI/GeoPaysages/releases/tag/v1.3.0)
