### ISSUE TITLE
Liste des points d'observation / Améliorations filtres

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoPaysages#75]
- Revoir le nom de la page et de sa route (https://github.com/PnX-SI/GeoPaysages/issues/9)
- Rajouter un compteur : nombre de points d'observation (Points d'observation (nb)) s'adaptant quand on filtre
- Ajouter un indicateur quand des filtres sont activés (point rouge sur type de filtre)
- Ne pas afficher "référence" si non renseignée

**Comment by camillemonchicourt** [comment]
- OK pour le nom de route
- OK pour le compteur. A voir cependant si on l'ajoute comme réalisé, ou si on ajoute juste un compteur entre parenthèse en haut de la liste des sites : "Sites d'observation (nombre)" ?
- Renommer "Points d'observation" en "Sites d'observation"
- L'indicateur de filtre ne semble pas fonctionner correctement. Il s'affiche seulement si on rafraîchit la page ? Et ne se désactive pas si on supprime les filtres ?
- Ajouter un bouton pour réinitialiser les filtres ?
- Si on n'a pas le champs "référence" renseigné, cela semble avoir été géré désormais. Et un paramètre a été ajouté pour choisir si les filtres sont triés par nom ou par référence ?

**Comment by 20cents** [comment]
> OK pour le compteur. A voir cependant si on l'ajoute comme réalisé, ou si on ajoute juste un compteur entre parenthèse en haut de la liste des sites : "Sites d'observation (nombre)" ?
- J'attend une décision

> L'indicateur de filtre ne semble pas fonctionner correctement. Il s'affiche seulement si on rafraîchit la page ? Et ne se désactive pas si on supprime les filtres ?
- ça devrait être bon

> Ajouter un bouton pour réinitialiser les filtres ?
- Tu ne vois pas la petite croix à côté du nombre du résultats ? La rendre plus visible ?

> Et un paramètre a été ajouté pour choisir si les filtres sont triés par nom ou par référence ?
- Oui

**Comment by camillemonchicourt** [comment]
OK pour le fonctionnement actuel des filtres.
Reste juste à renommer sur la page d'accueil en "Explorer les sites d'observation". Et renommer dans le README et la doc d'installation.

**Comment by 20cents** [comment]
@camillemonchicourt TOCHECK
