### ISSUE TITLE
Liste des photos d'un site / Filtre ou calendrier ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoPaysages#77]
Pour les suivis scientifiques de sites, on peut avoir beaucoup de photos sur un seul site (2000), voir si il est utile de filtrer les photos proposées. Afficher un date_picker ne proposant que les dates où il y a une photo ? Pouvoir n'afficher qu'une photo par mois ou semaine ?

A étudier et maquetter en lien avec https://github.com/PnX-SI/GeoPaysages/issues/76

**Comment by camillemonchicourt** [comment]
Un filtre par date avec un calendrier a été mis en place. Voir http://vps587786.ovh.net/sites/3
A valider.

**Comment by camillemonchicourt** [comment]
La navigation, la recherche et la sélection d'une date pourrait être amélioré
- Afficher seulement 10 dates par page pour bien fonctionner sur un écran de PC portable classique ? Plutôt que 15 ? Paramétrable ?
- Les filtres entre 2 dates sont assez lourds à utiliser. On préférerait que le calendrier serve à rapidement choisir une date précise. Mais cela nécessite de ne permettre de sélectionner que les dates qui ont une image. 
- On aimerait pouvoir naviguer plus facilement entre les dates. A minima avoir un bouton "Précédent" / "Suivant" allant directement à l'image précédente ou suivante. Et idéalement pouvoir aussi passer de mois en mois ou d'année en année si les images sont disponibles. Voir exemple de navigation entre date avec pas paramétrable sur cet exemple : https://worldview.earthdata.nasa.gov/
![image](https://user-images.githubusercontent.com/4418840/92740325-f54ac100-f37d-11ea-8563-d3eb97ec9666.png)

**Comment by 20cents** [comment]
@camillemonchicourt 
- Ajout des boutons prev, next, plus un sélecteur de pas.
cf #76

**Comment by camillemonchicourt** [comment]
OK super pour les boutons PREVIOUS / NEXT. C'est impeccable.
Quelques remarques : 
- Ajouter un paramètre pour afficher ou non le sélecteur de pas. Ceux qui ont un observatoire photo classique ne voudraient peut-etre qu'un usage photo précédente / suivante, sans pas
- Afficher le selecteur de pas entre les boutons Précédent et Suivant. Ou même plutôt le bouton Précédent / Suivant encadrant la date
- Cela a cassé le responsive, on ne peut plus changer la date sur un mobile

**Comment by camillemonchicourt** [comment]
Pour les filtres entre 2 dates, on laisse comme ça.
Reste l'autre point évoqué : 
- Afficher seulement 10 dates par page pour bien fonctionner sur un écran de PC portable classique ? Plutôt que 15 ? Paramétrable ?

**Comment by 20cents** [comment]
@camillemonchicourt 
- Responsive réparé
- ça n'a pas trop de sens de rendre le nombre de date par page paramétrable en base, non ? Plutôt un param pour l'utilisateur front à prévoir dans un futur dev ?

**Comment by camillemonchicourt** [comment]
OK merci pour le responsive. OK pour le passage à 10 dates par page, c'est mieux. Pas essentiel de pouvoir le paramétrer en effet. On met ça de côté en effet et on le laisse fixe à 10 pour le moment.

**Comment by camillemonchicourt** [comment]
Paramètre ajouté dans la PR - https://github.com/PnX-SI/GeoPaysages/pull/103
