### ISSUE TITLE
Embed dernière image dans site externe

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoPaysages#78]
Pouvoir intégrer la dernière photo d'un site dans un site web externe (parc national, partenaire...).

Créer une petite page web simple contenant la dernière photo d'un site (en 100% de large pour s'adapter au site où elle est intégrée) + sa date et son auteur et copyright

**Comment by 20cents** [comment]
http://vps587786.ovh.net/sites/1/photos/last

**Comment by camillemonchicourt** [comment]
OK super.
Merci pour cette fonctionnalité. 
Oubli de ma part, si il est possible d'ajouter le nom du site avant la date ? "Nom site - Date photo © Auteur copyright

Aussi si je peux chipoter sur le vocabulaire : 
En anglais, last = Dernier, au sens du final, il n'y en a pas d'autres après
Laster = Dernier, au sens du plus récent
Donc remplacer "/last" par "/latest" si possible ?

Merci.

**Comment by 20cents** [comment]
Ok c'est fait

**Comment by camillemonchicourt** [comment]
OK pour moi : http://vps587786.ovh.net/sites/1/photos/latest
Merci.
