### ISSUE TITLE
Nom route site à revoir ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoPaysages#8]
C'est étonnant que la route d'un site soit nommé /comparator/
Il s'agit de la fiche d'un site, le comparateur n'est qu'un outil dans celle-ci.

Plutôt afficher les fiches des sites sur une route de type http://domain/site/5

Idem pour le titre des fiches de chaque site qui indique en premier "COMPARAISON DE PHOTOS". 
C'est juste la fiche du site.

**Comment by 20cents** [comment]
J'ai renommé comparator en site.
Du coup j'ai renommé certains fichiers pour que tout soit homogène.
Il faut peut-être lancer ces commandes depuis la racine du projet :
pybabel extract -F ./backend/babel.cfg -o ./backend/i18n/messages.pot ./backend
pybabel update -i ./backend/i18n/messages.pot -d ./backend/i18n
pybabel compile -d ./backend/i18n

**Comment by camillemonchicourt** [comment]
Fait https://github.com/PnX-SI/GeoPaysages/commit/1c640ce43d427fd285aa1766b08561e246b47527
