### ISSUE TITLE
Interprétation des retours à la ligne et formatage des champs de texte

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoPaysages#82]
Les retours à la ligne dans les champs de textes ne sont pas interprétés dans la fiche d'un site (présentation et témoignage).

Comme ce sont les deux seuls attributs dans lesquels on peut intégrer du contenu descriptif, il serait très utile de pouvoir styliser et structurer un peu le contenu ces blocs de textes.

A minima en interprétant les caractères de saut de ligne (`\n`) voire, idéalement, en interprétant de l'HTML (avec un éditeur simple côté backoffice).

**Un exemple dans notre contexte :** 
Différents champs de notre BD historique contiennent des textes (analyses paysagère du site) que j'ai concaténés selon une certaine structure pour voir (incluant des sauts de lignes).

Aperçu du rendu d'un même texte : 

- dans la fiche du site (sans les sauts de lignes) : 

![image](https://user-images.githubusercontent.com/16793813/84391689-99935f00-abf9-11ea-925e-0d47f9e46fac.png)

-  dans le champ de texte ad-hoc du backoffice (avec les sauts de lignes) : 

![image](https://user-images.githubusercontent.com/16793813/84391767-b2037980-abf9-11ea-8770-214f60062fd1.png)

**Comment by 20cents** [comment]
@camillemonchicourt pour l'instant j'ai fais simple, le contenue des champs **description** et **témoignage** (du site) n'est plus auto-échappé par jinja, le HTML est donc interprété par le browser.
Du coup pour faire un retour à ligne il faut mettre un `<br />`

**Comment by camillemonchicourt** [comment]
OK merci. Ça permet d'afficher de la mise en forme dans les textes.
Pour que cela soit vraiment utilisable par des utilisateurs non techniciens, la solution de @xavyeah39 d'intégrer un WYSIWYG dans l'admin des champs texte est idéale, mais à creuser plus tard.

**Comment by Chrispnv** [comment]
Bonjour @20cents 
Peux tu être plus explicite sur le pis-aller que tu as mis en oeuvre ?
J'ai simplement édité un site en rajoutant un <br /> ou un <br> à la fin d'une phrase depuis le back office. Celui-ci n'est pas interprété. Il n'y a pas de saut de ligne et le <br> apparait.
Est ce qu'il y a une config à faire sur "Jinja" ou autre ?
Merci.

**Comment by camillemonchicourt** [comment]
Tous ces développements sont faits dans la branche ``dev`` que l'on doit tester pour faire une release de la version 1.1.0 : https://github.com/PnX-SI/GeoPaysages/blob/dev/docs/changelog.rst
On a pas encore pris le temps de faire ces tests et cette release, en attente depuis plusieurs mois, mais on doit le faire cet été.

**Comment by xavyeah39** [comment]
Fait dans cd06dc3
