### ISSUE TITLE
Configuration des fonds de cartes

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/GeoPaysages#83]
Les configurations des fonds de cartes sont gérées différemment selon les pages qui appellent des cartes Leaflet.

Dans la "carte intéractive" (/map) et dans la fiche du site (/comparator) c'est géré tel que décrit dans la doc avec des entrées dans la table `geopaysages.conf` de la BD. Facile à modifier, nickel !

Mais le comportement est différent pour les cartes suivantes car c'est géré en dur dans les fichiers JS ad-hoc : 
- mini-carte de la homepage (`./backend/static/js/home.js`)
- carte du gestionnaire des sites du backoffice (`./front-backOffice/src/app/manage-sites/manage-sites.component.ts`)
- carte de la fiche d'un site du backoffice (`./front-backOffice/src/app/add-site/add-site.component.ts`)

Ne serait-il pas possible/judicieux d'homogénéiser cela pour que toutes les conf des fonds de cartes (et le fond par défaut) soit gérées comme pour la carte intéractive (dans la table `geopaysages.conf`) ?

**Comment by camillemonchicourt** [comment]
Oui en effet.

**Comment by camillemonchicourt** [comment]
Et supprimer le paramètre ``ignkey``.

**Comment by xavyeah39** [comment]
La conf des fonds de cartes a été centralisé en [v1.3.0](https://github.com/PnX-SI/GeoPaysages/releases/tag/v1.3.0).
Le paramétrage est désormais géré en BDD via la table `geopaysages.conf` et le paramètre `map_layers` [documenté ici](https://github.com/PnX-SI/GeoPaysages/blob/master/docs/personnalisation.md#configuration-en-base-de-donn%C3%A9es).
