### ISSUE TITLE
Erreur installation Postgres / Postgis sur Debian 10

### ISSUE THREAD

**Issue by 20cents** [PnX-SI/GeoPaysages#88]
En installant l'app sur Debian 10, cette commande lancée par **install_env.sh** à échouée :
`sudo apt-get install postgresql postgresql-contrib postgis postgresql-9.6-postgis-2.3 postgresql-9.6-postgis-2.3-scripts`

A la place j'ai fais : 
`sudo apt-get install postgresql` 
`sudo apt-get install postgis postgresql-11-postgis-2.5`

On dirai que ça fait le job.

**Comment by HamoudaAmine** [comment]
Oui effectivement dans la documentation il est noté dans les prérequis que que l'application développée et installée sur un serveur Debian 9.
Donc il faut faire attention aux changements des versions pour debian 10 et Ubuntu 20

**Comment by camillemonchicourt** [comment]
OK, dans le script il est possible d'identifier la version de l'OS pour installer une version de PG ou l'autre en fonction de l'OS.
Gérer Debian 9 et 10 serait bien pour le moment.

**Comment by camillemonchicourt** [comment]
Exemple ici : https://github.com/PnX-SI/GeoNature/blob/master/install/install_all/install_all.sh#L77-L99

**Comment by xavyeah39** [comment]
Obsolète avec la conteneurisation Docker de PostgreSQL/PostGIS en [v1.3.0](https://github.com/PnX-SI/GeoPaysages/releases/tag/v1.3.0)
