### ISSUE TITLE
Mise à jour auto vers v1.0.0

### ISSUE THREAD

**Issue by 20cents** [PnX-SI/GeoPaysages#89]
#### Pour ceux qui veulent faire une mise à jour vers v1.0.0 via le script **update_app.sh**
Il y a une ligne en plus dans le fichier **/front-backOffice/src/app/config.ts.tpl** 
`customFiles: '<server_name>/static/custom/'`
Avant de lancer **update_app.sh** il faut ajouter cette ligne dans le fichier existant **/front-backOffice/src/app/config.ts**

**Comment by camillemonchicourt** [comment]
OK merci, je viens de l'indiquer dans les notes de version : https://github.com/PnX-SI/GeoPaysages/releases

**Comment by camillemonchicourt** [comment]
Indiqué dans les notes de version de la 1.0.0 et dans le nouveau fichier de suivi CHANGELOG : https://github.com/PnX-SI/GeoPaysages/blob/dev/docs/changelog.rst
