### ISSUE TITLE
Page Carte interactive et routes

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/GeoPaysages#9]
Là aussi je dirai qu'il y a un problème d’appellation. 

Car là aussi, la carte est juste un outil mais pas le contenu, donc pas le bon nom de route ni de page. 
Il s'agit de la page de recherche, ou la page des sites. 
La route devrait être http://domain/sites/ ou http://domain/search

Le nom de la page dans le Menu et son titre quand on l'affiche devraient être : "Les sites" (de préférence) ou "Rechercher un site". 

Et sur cette page, les filtres ne me semblent pas très ergonomiques. Et la recherche d'un site n'est pas simple car il manque la liste des sites, avec une interaction Carte <> Liste. C'est peut-être prévu ?

Je pense que j'aurai construit cette page sur ce modèle : 
Bandeau vertical de filtres en haut (avec des listes déroulantes à choix multiples)
Liste à gauche / Carte à droite (ou inversement)

**Comment by camillemonchicourt** [comment]
On propose de renommer la page en "Points d'observation" et la route en cohérence.
Sur la HOME, on renomme "Explorer la carte interactive" en "Explorer les points d'observation".

**Comment by xavyeah39** [comment]
> Bandeau vertical de filtres en haut (avec des listes déroulantes à choix multiples)

Tu voulais dire horizontal ?

**Comment by camillemonchicourt** [comment]
Mais on ne parlera pas de "Points d'observations" mais bien de "Sites d'observation" comme évoqué par ailleurs.

**Comment by 20cents** [comment]
La route est à présent /sites
Le titre c'est LES SITES D'OBSERVATION
