### ISSUE TITLE
Nom des routes

### ISSUE THREAD

**Issue by 20cents** [PnX-SI/GeoPaysages#93]
On a renommé /comparator/:id en /site/:id
C'est pas mal, mais on aurait plutôt dû faire /sites/:id
Ainsi la page /map pourrait devenir /sites et là on aurait quelque chose de logique.
Non ?

**Comment by camillemonchicourt** [comment]
OK en lien avec https://github.com/PnX-SI/GeoPaysages/issues/9
Oui pour que la page ``/map`` devienne ``/sites``
Et pour la fiche détail d'un site ``/site/:id`` ou ``/sites/:id`` me vont dans les 2 cas.

**Comment by camillemonchicourt** [comment]
Fait
